project:
  type: book

book:
  title: "STAT638: Applied Bayesian Methods"
  author: "Shao-Ting Chiu (stchiu@email.tamu.edu)"
  repo-url: https://github.com/stevengogogo/STAT638_Applied-Bayes-Methods
  date: today
  favicon: img/favicon.png
  chapters:
    - index.qmd
    - part: "**Lecture Notes**"
      chapters:
      - ch1.qmd
      - ch2.qmd
      - ch3.qmd
      - ch4.qmd
    - part: "**Assignments**"
      chapters:
      - hw/hw1.qmd
      - hw/hw2.qmd
      - hw/hw3.qmd
      - hw/hw4.qmd
      - hw/hw5.qmd
      - hw/hw6.qmd
      - hw/hw7.qmd
      - hw/hw8.qmd
      - hw/hw9.qmd
      - hw/hw10.qmd
    - ref.qmd

bibliography: ref.bib

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    code-tools:
            source: true




