project:
  type: book

book:
  title: "STAT638: Applied Bayesian Methods"
  author: "Shao-Ting Chiu"
  date: "8/25/2022"
  chapters:
    - index.qmd
    - ch1.qmd
    - ch2.qmd
    - hw/hw1.qmd
    - hw/hw2.qmd
    - summary.qmd
    - analy/analy.ipynb
    - ref.qmd

bibliography: ref.bib

format:
  html:
    theme: cosmo



