project:
  type: book

book:
  title: "STAT638: Applied Bayesian Methods"
  author: "Shao-Ting Chiu (stchiu@email.tamu.edu)"
  repo-url: https://github.com/stevengogogo/STAT638_Applied-Bayes-Methods
  date: today
  favicon: img/favicon.png
  chapters:
    - index.qmd
    - ch1.qmd
    - ch2.qmd
    - ch3.qmd
    - hw/hw1.qmd
    - hw/hw2.qmd
    - summary.qmd
    - analy/analy.ipynb
    - ref.qmd

bibliography: ref.bib

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    code-tools:
            source: true




