project:
  type: book

book:
  title: "STAT638: Applied Bayesian Methods"
  author: "Jane Doe"
  date: "8/25/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - hw1.md
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



