project:
  type: book

book:
  title: "STAT638: Applied Bayesian Methods"
  author: "Jane Doe"
  date: "8/25/2022"
  chapters:
    - index.qmd
    - ch1.qmd
    - ch2.qmd
    - hw1.qmd
    - summary.qmd
    - analy/analy.ipynb
    - ref.qmd

bibliography: ref.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



